CORE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.reservacion.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/reservacion/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from apps.reservacion.views import (
    Home, HomeMenu, ReservacionView, 
    ReservacionForm, HabitacionView, 
    InventarioView, ClientesView, MisReservaciones,NewAdminUser,
    NewUser, ViewPagoMovil, VentasForm, ListadoVentas, MenuReportes
)

#reportes
from apps.reservacion.reportes import ReporteClientes, ReporteReservacion, ReporteReservacionHabitacion, ReporteTurnos

app_name = 'reservacion'
urlpatterns = [
    # LandingPage
    path('', Home.as_view(), name='home'),
    # registro de clientes por la plataforma
    path('registro-de-clientes/', NewUser.as_view(), name='register'),

    
    path('inicio/', HomeMenu.as_view(), name='menu'),
    path('reservaciones/', ReservacionView.as_view(), name='reservacion'),
    path('mis-reservaciones/', MisReservaciones.as_view(), name='mi_reservacion'),
    path('nueva-reservacion/', ReservacionForm.as_view(), name='new_reservacion'),
    path('habitaciones/', HabitacionView.as_view(), name='habitacion'),
    path('inventario/', InventarioView.as_view(), name='inventario'),
    path('clientes/', ClientesView.as_view(), name='clientes'),
    path('lista-de-pagomovil/', ViewPagoMovil.as_view(), name='pago_movil'),
    path('registro-de-administradores/', NewAdminUser.as_view(), name='admin_register'),

    # ventas
    path('listado-de-venta/', ListadoVentas.as_view(), name='ventas_list'),
    path('registro-de-venta/', VentasForm.as_view(), name='ventas_form'),

    # reportes
    path('menu-de-reportes/', MenuReportes.as_view(), name='reportes'),
    path('reporte-de-clientes/', ReporteClientes.as_view(), name='re_cliente'),
    path('reporte-de-reservaciones/<str:id>/', ReporteReservacion, name='re_reservaciones'),
    path('reporte-de-reservaciones-por-habitaciones/', ReporteReservacionHabitacion, name='re_reservaciones_habi'),
    path('reporte-por-turnos/<str:fecha1>/<str:fecha2>/', ReporteTurnos, name='re_turnos'),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/reservacion/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.forms import model_to_dict
from datetime import datetime, date, timedelta

# Create your models here.

estado_reserva = (
    ('Aprobada','Aprobada'),
    ('Pendiente', 'Pendiente'),
    ('Rechazada', 'Rechazada'),
)
estado_habitacion = (
    ('Disponible','Disponible'),
    ('Ocupada', 'Ocupada'),
    ('Reservada', 'Reservada'),
    ('Mantenimiento', 'Mantenimiento'),
    ('Inhabilitada', 'Inhabilitada'),
)

class Clientes(AbstractUser):
	cedula = models.CharField(max_length=8, primary_key=True, unique=True, blank=False, null=False)
	nombre = models.CharField(max_length=50, blank=False, null=False)
	apellido = models.CharField(max_length=50,  blank=False, null=False)
	direccion = models.CharField(max_length=50,  blank=True, null=True)
	telefono = models.CharField(max_length=11, blank=True, null=True)

	def __str__(self):
		return f"{self.nombre} {self.apellido}"

	def toJSON(self):
		item = model_to_dict(self)
		return item

	class Meta:
		verbose_name = 'Cliente'
		verbose_name_plural = 'Clientes'

class Habitacion(models.Model):
	numeroHabitacion = models.IntegerField(primary_key=True)
	clase = models.CharField(max_length=50, blank=False, null=False)
	tipoHabitacion = models.CharField(max_length=25)
	estado = models.CharField(max_length=25, blank=False, null=False)
	precio = models.IntegerField()
	descripcion = models.TextField()

	def __str__(self):
		return f"{self.numeroHabitacion}"

	def toJSON(self):
		item = model_to_dict(self)
		return item

	class Meta:
		verbose_name = 'Habitacion'
		verbose_name_plural = 'Habitaciones'


class Reserva(models.Model):
	estado = models.CharField(max_length=25, choices=estado_reserva, default='Pendiente')
	fechaReserva = models.DateTimeField(auto_now_add=True)
	cliente = models.ForeignKey(Clientes, on_delete=models.PROTECT)
	origen = models.CharField(max_length=25, null=True, blank=True)

	def __str__(self):
		return f"{self.id}"

	def toJSON(self):
		item = model_to_dict(self)
		item['fechaReserva'] = self.fechaReserva.strftime('%d/%m/%Y, %H:%M')
		item['cliente'] = {'nombre':self.cliente.nombre, 'apellido':self.cliente.apellido, 'ci':self.cliente.cedula}
		return item
		

	class Meta:
		verbose_name = 'Reserva'
		verbose_name_plural = 'Reservas'

class DetalleReserva(models.Model):
	codigoReserva = models.ForeignKey(Reserva, on_delete=models.CASCADE)
	fechaLlegada = models.DateTimeField(null=False, blank=False)
	fechaSalida = models.DateTimeField(null=False, blank=False)
	habitacion = models.ForeignKey(Habitacion, on_delete=models.CASCADE, related_name='habitacion')
	cantidad = models.FloatField()
	total_bs = models.FloatField()

	def __str__(self):
		return f"{self.id}"

	def toJSON(self):
		item = model_to_dict(self)
		item['habitacion'] = {'numero': self.habitacion.numeroHabitacion}
		item['fechaLlegada'] = self.fechaLlegada.strftime('%d/%m/%Y, %H:%M')
		item['fechaSalida'] = self.fechaSalida.strftime('%d/%m/%Y, %H:%M')
		return item

class Productos(models.Model):
	nombre_pro = models.CharField(max_length=50, null=False, blank=False)
	descripcion = models.TextField(null=True, blank=True)
	stock = models.IntegerField(null=False, blank=False)
	precio = models.FloatField(null=False, blank=False)

	def __str__(self):
		return f"{self.nombre_pro}"

	def toJSON(self):
		item = model_to_dict(self)
		return item

	class Meta:
		verbose_name = 'Producto'
		verbose_name_plural = 'Productos'

class PrecioDolar(models.Model):
	code = models.CharField(default='dolar', max_length=50, primary_key=True, blank=False, null=False) 
	precio = models.FloatField(blank=False, null=False)

	def __str__(self):
		return f'{self.precio}'

	class Meta:
		verbose_name = 'Precio Dolar'

class DatosPagoMovil(models.Model):
	banco = models.CharField(null=False, blank=False, max_length=50)
	telefono = models.CharField(null=False, blank=False, max_length=50)
	cedula = models.CharField(null=False, blank=False, max_length=50)

	def __str__(self):
		return f"{self.banco}"

	def toJSON(self):
		item = model_to_dict(self)
		return item

	class Meta:
		verbose_name = 'Pago Movil'

# VENTAS

class Venta(models.Model):
	fecha_venta = models.DateTimeField(null=False, blank=False, auto_now_add=True)
	vendedor = models.ForeignKey(Clientes, on_delete=models.PROTECT, null=False, blank=False)
	reservacion = models.ForeignKey(Reserva, on_delete=models.PROTECT, null=True, blank=True)
	total_dolar = models.FloatField(null=False, blank=False)
	total_bs = models.FloatField(null=False, blank=False)

	def __str__(self):
		return str(self.id)

	def toJSON(self):
		item = model_to_dict(self)
		item['fecha_venta'] = self.fecha_venta.strftime('%d/%m/%Y, %H:%M')
		return item

	class Meta:
		verbose_name = 'Venta'
		verbose_name_plural = 'Ventas'

class DetVenta(models.Model):
	venta = models.ForeignKey(Venta, on_delete=models.PROTECT, null=False, blank=False)
	producto = models.ForeignKey(Productos, on_delete=models.PROTECT, null=False, blank=False)
	precio = models.FloatField(null=False, blank=False)
	cantidad = models.IntegerField(null=False, blank=False)
	total_cantidad = models.FloatField(null=False, blank=False)

	def __str__(self):
		return str(self.id)

	def toJSON(self):
		item = model_to_dict(self)
		item['producto'] = {'nombre': self.producto.nombre_pro, 'precio': self.producto.precio}
		item['venta'] = {'total_bs': self.venta.total_bs, 'total_dolar': self.venta.total_dolar}
		return item

	class Meta:
		verbose_name = 'Detales de venta'
		verbose_name_plural = 'Detalles de ventas'

templates/pages/habitacion/habitacion.html
{% extends "MenuPage.html" %}
{% load static %}
{% block title %}Habitaciones{% endblock title %}
{% block content %}
{% if request.user.is_staff %}
	<div class="card p-3">
		<h5 class="card-header">Listado de Habitaciones</h5>
		<div class="table-responsive text-nowrap">
			<div class="card-title d-flex align-items-start justify-content-between">
				<div class="avatar flex-shrink-0">
		  
				</div>
				<div class="dropdown">
					<button class="btn p-0" type="button" id="cardOpt1" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						<i class="bx bx-dots-vertical-rounded"></i>
					</button>
					<div class="dropdown-menu" aria-labelledby="cardOpt1">
						<button class="dropdown-item" tabindex="-1" onclick="abrir_modal_habitacion();">Agregar</button>
					</div>
				</div>
			</div>
			<table id="Habitacion" class="table table-striped table-bordered" style="width:100%">
				<thead>
					<tr>
						<th>Nº Habitación</th>
						<th>Duración</th>
						<th>T. Habitación</th>
						<th>Precio</th>
						<th>Estado</th>
						<th>Descripción</th>
						<th>Opciones</th>
					</tr>
				</thead>
				<tbody>
				</tbody>
			</table>
		</div>
	</div>


	<!-- Modales -->

	<div class="col-lg-4 col-md-3">
		<!-- Modal -->
		<div class="modal fade" id="modal_habitacion" data-bs-backdrop="static" tabindex="-1" aria-hidden="true" style="display: none;">
		  <div class="modal-dialog">
			<form class="modal-content" id="habitacion_form">{% csrf_token %}
				<input type="hidden" name="action" value="new_habitacion">
				<input type="hidden" name="id" value="0">
			  <div class="modal-header">
				<h5 class="modal-title" id="backDropModalTitle">Registrar Habitación</h5>
				<button type="button" class="btn-close" onclick="cerrar_modal_habitacion();"></button>
			  </div>
			  <div class="modal-body">
				<div class="row g-2">
					<div class="col mb-3">
				  	<label for="id_clase" class="form-label">Tipo de Duración</label>
				  	<select class="form-control" name="clase" id="id_clase" required>
				  		<option value="">--Seleccione duración--</option>
				  		<option value="Corta duracion">Corta Duración</option>
				  		<option value="Larga duracion">Larga Duración</option>
				  	</select>
				  </div>
				  <div class="col mb-3">
					<label for="id_tipoHabitacion" class="form-label">Tipo de Habitación</label>
					<select id="id_tipoHabitacion" name="tipoHabitacion" class="form-control" required>
						<option value="">--Seleccione el tipo--</option>
						<option value="Normales">Normales</option>
						<option value="Especiales">Especiales</option>
						<option value="Porton" class="ocultar">Portón</option>
						<option value="Junior">Junior</option>
					</select>
				  </div>
				</div>
				<div class="row g-2">
				  <div class="col mb-0">
					<label for="id_numeroHabitacion" class="form-label">Numero de Habitación</label>
					<input type="number" min="0" id="id_numeroHabitacion" name="numeroHabitacion" class="form-control" placeholder="Numero de Habitación" required>
				  </div>
				  <div class="col mb-0">
					<label for="id_precio" class="form-label">Precio</label>
					<input type="number" min="1" id="id_precio" name="precio" class="form-control" placeholder="Precio de la habitacion" required>
				  </div>
				</div>
				<div class="row mt-3">
					<label for="id_estado" class="form-label">Estado de la habitacion</label>
					<select name="estado" id="id_estado" class="form-control" required>
						<option value="">--Seleccione el estado--</option>
						<option selected value="Disponible">Disponible</option>
						<option value="Ocupada">Ocupada</option>
						<option value="Mantenimiento">Mantenimiento</option>
					</select>
				</div>
				<div class="row mt-3">
					<label class="form-label" for="id_descripcion">Descripción</label>
					<textarea class="form-control" id="id_descripcion" name="descripcion" placeholder="Descripción de la habitacion" required onkeypress="return Texto_Numeros(event);"></textarea>
				</div>
			  </div>
			  <div class="modal-footer">
				<button type="button" class="btn btn-outline-secondary" onclick="cerrar_modal_habitacion();">
				  Cerrar
				</button>
				<button type="submit" class="btn btn-primary">Guardar</button>
			  </div>
			</form>
		  </div>
		</div>
	  </div>
	</div>

{% else %}
<div class="misc-wrapper">
    <h2 class="mb-2 mx-2">La página no Funciona :(</h2>
    <p class="mb-4 mx-2">Oops! 😖 No tienes permiso para ingresar a esta sección.</p>
    <a href="{% url 'reservacion:menu' %}" class="btn btn-primary">Regresar al Inicio</a>
    <div class="mt-3">
        <img
            src="{% static 'MenuBase/img/error_page.png' %}"
            alt="page-misc-error-light"
            width="500"
            class="img-fluid"
        />
    </div>
</div>
{% endif %}

{% endblock content %}
{% block js %}
	<script src="{% static 'MenuBase/js/pages/js_habitacion.js' %}"></script>
{% endblock js %}